### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by cuducos**
I start this license discussion suggesting GPL-3.0. But as I'm a noob in that topic, any pros, cons or other better suggestions?

cc @Irio @ncortezrj @leportella @cabral @jtemporal @anaschwendler @turicas @berinhard

### CODE REVIEW

**Comment by turicas** [comment]
For applications I usually use GPL3 and libraries LGPL3. I think any free software license having copyleft will be good for the project.

**Comment by jtemporal** [comment]
also newbie on the subject here but I agree with @turicas on this:

> any free software license having copyleft will be good for the project

:wink:

**Comment by berinhard** [comment]
I'm creating an open application recently that I'm planning to use GPL3 too.

**Comment by leportella** [comment]
I have no experience on this but I think we have an agreement that this license is good for us.  What do you think?

**Comment by cuducos** [comment]
> What do you think?

I think we can merge this ; )

**Comment by cuducos** [comment]
> What do you think?

I think we can merge this ; )

**Comment by leportella** [comment]
Done

**Pull request merged**
